/**
 * Cross-language canonicalisation check.
 *
 * Verifies the TypeScript implementation against the golden set generated by
 * the Python reference implementation. This is the gate the migration plan
 * (E2-2) requires before any domain code is ported: if these two disagree,
 * every approval binding and audit chain produced by the extension would
 * differ from the ones the Python implementation issued.
 *
 * Run with:
 *   node --experimental-strip-types extension/scripts/verify-canonical.ts
 *
 * Exits non-zero on the first mismatch, printing the case name, the expected
 * canonical form, and the produced one — escaped, so a terminal that cannot
 * render the character still shows the difference.
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

import { canonicalDigest, canonicalDigestSync, canonicalJson } from "../src/domain/canonical.ts";

interface GoldenCase {
  name: string;
  payload: unknown;
  canonical: string;
  digest: string;
}

interface Golden {
  rules: string[];
  cases: GoldenCase[];
}

const here = dirname(fileURLToPath(import.meta.url));
const goldenPath = resolve(
  here,
  "../../backend/tests/fixtures/canonical/golden.json",
);

function escapeForTerminal(value: string): string {
  return Array.from(value)
    .map((character) => {
      const point = character.codePointAt(0)!;
      if (point < 0x20 || point === 0x7f) {
        return `\\u${point.toString(16).padStart(4, "0")}`;
      }
      if (point > 0x7e) {
        return `\\u{${point.toString(16)}}`;
      }
      return character;
    })
    .join("");
}

async function main(): Promise<void> {
  const golden = JSON.parse(readFileSync(goldenPath, "utf8")) as Golden;
  const failures: string[] = [];

  for (const testCase of golden.cases) {
    let produced: string;
    try {
      produced = canonicalJson(testCase.payload);
    } catch (error) {
      failures.push(`${testCase.name}: threw ${(error as Error).message}`);
      continue;
    }

    if (produced !== testCase.canonical) {
      failures.push(
        `${testCase.name}: canonical form differs\n` +
          `    expected ${escapeForTerminal(testCase.canonical)}\n` +
          `    produced ${escapeForTerminal(produced)}`,
      );
      continue;
    }

    const digest = await canonicalDigest(testCase.payload);
    if (digest !== testCase.digest) {
      failures.push(
        `${testCase.name}: digest differs\n` +
          `    expected ${testCase.digest}\n` +
          `    produced ${digest}`,
      );
      continue;
    }

    // The synchronous digest is what runs inside IndexedDB transactions. If it
    // ever drifted from crypto.subtle, the audit chain written to storage would
    // stop matching the one the Python implementation verifies.
    const sync = canonicalDigestSync(testCase.payload);
    if (sync !== testCase.digest) {
      failures.push(
        `${testCase.name}: synchronous digest differs from crypto.subtle\n` +
          `    expected ${testCase.digest}\n` +
          `    produced ${sync}`,
      );
    }
  }

  if (failures.length > 0) {
    console.error(`FAIL ${failures.length}/${golden.cases.length} case(s)\n`);
    for (const failure of failures) console.error(`  ${failure}`);
    process.exit(1);
  }

  console.log(`OK ${golden.cases.length} cases match the Python reference.`);
}

await main();
