"""Regenerate the cross-language audit chain golden set.

Run from the repository root:

    python secure-gateway-studio/backend/tests/fixtures/audit/generate.py

The audit chain is what makes the event log evidence rather than a list: each
event carries the digest of the one before it, so an edited or removed event
invalidates everything after it. The extension writes that chain into
IndexedDB, and the Python implementation is what verifies exported evidence,
so the two must compute identical digests over identical records.

This pins a chain built by `StateRepository._audit_hash` itself, rather than a
re-implementation, so the golden cannot drift from the code it documents.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

_BACKEND_SRC = Path(__file__).resolve().parents[3] / "src"
sys.path.insert(0, str(_BACKEND_SRC))

from sgstudio.domain.canonical import canonical_json  # noqa: E402
from sgstudio.storage.repository import StateRepository  # noqa: E402

EVENTS: list[dict[str, Any]] = [
    {
        "event_id": "11111111-1111-4111-8111-111111111111",
        "deployment_id": None,
        "event_type": "plan.consumed",
        "actor": "operator@example.com",
        "payload": {"approval_id": "a-1", "configuration_hash": "a" * 64},
        "created_at": "2026-08-04T00:00:00+00:00",
    },
    {
        "event_id": "22222222-2222-4222-8222-222222222222",
        "deployment_id": "d-1",
        "event_type": "run.started",
        "actor": "operator@example.com",
        "payload": {"run_id": "r-1", "approval_id": "a-1", "configuration_hash": "a" * 64},
        "created_at": "2026-08-04T00:00:01+00:00",
    },
    {
        # Non-ASCII actor and payload: the OU picker is bilingual, and this is
        # exactly where ensure_ascii would have diverged before the
        # canonicalisation was unified.
        "event_id": "33333333-3333-4333-8333-333333333333",
        "deployment_id": "d-1",
        "event_type": "acceptance.recorded",
        "actor": "管理者@example.com",
        "payload": {"summary": "組織部門/テスト で確認", "status": "user_confirmed"},
        "created_at": "2026-08-04T00:00:02+00:00",
    },
    {
        "event_id": "44444444-4444-4444-8444-444444444444",
        "deployment_id": None,
        "event_type": "run.interrupted",
        "actor": "system",
        "payload": {"run_id": "r-1", "configuration_hash": "a" * 64},
        "created_at": "2026-08-04T00:00:03+00:00",
    },
]


def build() -> dict[str, Any]:
    chain: list[dict[str, Any]] = []
    previous_hash: str | None = None
    for event in EVENTS:
        payload_json = canonical_json(event["payload"])
        event_hash = StateRepository._audit_hash(
            event_id=event["event_id"],
            deployment_id=event["deployment_id"],
            event_type=event["event_type"],
            actor=event["actor"],
            payload_json=payload_json,
            created_at=event["created_at"],
            previous_hash=previous_hash,
        )
        chain.append(
            {
                **event,
                "payload_json": payload_json,
                "previous_hash": previous_hash,
                "event_hash": event_hash,
            }
        )
        previous_hash = event_hash
    return {
        "note": (
            "Generated by generate.py from StateRepository._audit_hash. Verified by "
            "backend/tests/test_audit_golden.py and the extension audit test. "
            "Do not hand-edit."
        ),
        "chain_head_hash": previous_hash,
        "events": chain,
    }


def main() -> None:
    target = Path(__file__).with_name("golden.json")
    document = build()
    target.write_text(
        json.dumps(document, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    events = document["events"]
    assert isinstance(events, list)
    print(f"wrote a {len(events)}-event chain to {target.name}")


if __name__ == "__main__":
    main()
