"""Regenerate the cross-language canonicalisation golden set.

Run from the repository root:

    python secure-gateway-studio/backend/tests/fixtures/canonical/generate.py

The golden set pins the byte-for-byte output of ``canonical_json`` and the
resulting digest. Both the Python reference implementation and the TypeScript
port in the Chrome extension are verified against this same file, so it is the
single point where the two agree.

Regenerate deliberately. If a golden digest changes, every approval binding and
audit chain the product has ever issued changes with it.

Control characters and astral-plane characters are built with ``chr`` rather
than written literally, so this file contains no bytes an editor could mangle
and no escape sequence a reviewer has to decode.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

_BACKEND_SRC = Path(__file__).resolve().parents[3] / "src"
sys.path.insert(0, str(_BACKEND_SRC))

from sgstudio.domain.canonical import canonical_digest, canonical_json  # noqa: E402

GRINNING_FACE = chr(0x1F600)  # astral plane, encoded as a UTF-16 surrogate pair
NONCHARACTER = chr(0xFFFF)  # highest BMP code point
COMBINING_ACUTE = chr(0x0301)

CASES: list[tuple[str, object]] = [
    ("empty-object", {}),
    ("empty-array", []),
    ("flat-ascii", {"b": "two", "a": "one", "c": "three"}),
    (
        "key-order-is-normalised",
        {"zebra": 1, "Zebra": 2, "apple": 3, "Apple": 4, "_under": 5, "0digit": 6},
    ),
    ("nested", {"outer": {"inner": {"leaf": "value"}}, "sibling": [1, 2, 3]}),
    ("nulls-and-booleans", {"present": True, "absent": None, "off": False}),
    (
        "integers",
        {
            "zero": 0,
            "negative": -42,
            "large": 9007199254740991,
            "small": -9007199254740991,
        },
    ),
    ("empty-string-key-and-value", {"": "", "k": ""}),
    # DeploymentSpec.offload_cpu_target is the only float the product hashes.
    # Its ge=0.1/le=0.9 bound keeps it clear of whole numbers and of
    # exponential notation, the two places Python and JavaScript disagree.
    (
        "decimal-floats",
        {"offload_cpu_target": 0.6, "lower_bound": 0.1, "upper_bound": 0.9},
    ),
    # Shortest-round-trip agreement on a value whose repr is long.
    ("float-long-repr", {"accumulated": 0.1 + 0.2}),
    # The bilingual product accepts Japanese OU paths and deployment names.
    # These are the cases that diverge silently under ensure_ascii=True.
    ("japanese-values", {"ou": "組織部門/テスト"}),
    ("japanese-keys", {"部門": "value", "a": "ascii"}),
    ("mixed-script-key-sort", {"組織": 1, "apple": 2, "école": 3, "Zebra": 4}),
    # Python sorts keys by code point; JavaScript's default Array.sort compares
    # UTF-16 code units. An implementation that does not sort by code point
    # fails these two cases and only these two.
    ("non-bmp-emoji", {GRINNING_FACE: "grinning", "z": "ascii"}),
    ("non-bmp-vs-bmp-key-sort", {GRINNING_FACE: 1, NONCHARACTER: 2, "A": 3}),
    # Decomposed "e" + combining acute and precomposed U+00E9 are distinct
    # keys. Neither implementation may apply Unicode normalisation.
    (
        "combining-characters",
        {"e" + COMBINING_ACUTE: "decomposed", chr(0x00E9): "precomposed"},
    ),
    ("escapes", {"quote": '"', "backslash": "\\", "newline": "\n", "tab": "\t"}),
    (
        "control-characters",
        {
            "nul": chr(0x00),
            "bell": chr(0x07),
            "vertical-tab": chr(0x0B),
            "delete": chr(0x7F),
        },
    ),
    ("solidus-is-not-escaped", {"path": "a/b/c"}),
    (
        "array-of-objects-preserves-order",
        {"items": [{"b": 1, "a": 2}, {"d": 3, "c": 4}]},
    ),
    # SHA-256 padding bugs surface at message lengths near a 64-byte block
    # boundary. The extension carries a hand-written synchronous digest for use
    # inside IndexedDB transactions, so these lengths are exercised deliberately.
    ("block-boundary-55", {"a": "x" * 48}),
    ("block-boundary-56", {"a": "x" * 49}),
    ("block-boundary-63", {"a": "x" * 56}),
    ("block-boundary-64", {"a": "x" * 57}),
    ("block-boundary-65", {"a": "x" * 58}),
    ("multi-block", {"a": "x" * 500}),
    (
        "realistic-teardown-payload",
        {
            "run_id": "6f1d2c3b-4a59-4d8e-9f10-2b3c4d5e6f70",
            "configuration_hash": "a" * 64,
            "resources": [
                {"key": "compute.instanceGroupManagers/sg-mig", "action": "delete"},
                {"key": "dns.resourceRecordSets/app", "action": "delete"},
            ],
        },
    ),
]


def build() -> dict[str, object]:
    return {
        "note": (
            "Generated by generate.py. Verified by backend/tests/test_canonical.py "
            "and by the extension canonical test. Do not hand-edit."
        ),
        "rules": [
            "object keys sorted by Unicode code point",
            "separators are ',' and ':' with no whitespace",
            "non-ASCII emitted raw, never escaped",
            "floats rejected; integers only",
        ],
        "cases": [
            {
                "name": name,
                "payload": payload,
                "canonical": canonical_json(payload),
                "digest": canonical_digest(payload),
            }
            for name, payload in CASES
        ],
    }


def main() -> None:
    target = Path(__file__).with_name("golden.json")
    document = build()
    cases = document["cases"]
    assert isinstance(cases, list)
    target.write_text(
        json.dumps(document, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"wrote {len(cases)} cases to {target.name}")


if __name__ == "__main__":
    main()
